### ISSUE TITLE
drivers error

### ISSUE THREAD

**Issue by ghost** [SAM-tak/BlenderGameRig#11]
```
bpy.ops.object.armature_add(enter_editmode=False, align='WORLD', location=(0, 0, 0), scale=(1, 1, 1))
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.ops.gamerig.unity_mechanim_d_human_metarig_add()
bpy.ops.ui.copy_as_driver_button()
bpy.ops.object.posemode_toggle()
bpy.ops.object.posemode_toggle()
bpy.context.space_data.context = 'DATA'
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.transform_apply(location=False, rotation=True, scale=False)
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.ops.object.join()
bpy.ops.object.delete()
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
Python: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\gamerig\ui.py", line 662, in execute
    error = generate.generate_rig(context, context.object)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\gamerig\generate.py", line 386, in generate_rig
    raise e
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\gamerig\generate.py", line 331, in generate_rig
    copy_attributes(d1.driver, d2.driver)
AttributeError: 'list' object has no attribute 'driver'

location: <unknown location>:-1


```
![1](https://user-images.githubusercontent.com/60543373/160537872-fa8ed3f9-bbe2-4871-8e45-f18fc3234123.jpg)

![2](https://user-images.githubusercontent.com/60543373/160537877-59a90ae5-2dda-404c-952e-744011a71928.jpg)

![3](https://user-images.githubusercontent.com/60543373/160537886-ab81d8cf-68ac-4344-99fd-e50f157ab07f.jpg)

**Comment by SAM-tak** [comment]
it maybe fixed.

please try latest release!
https://github.com/SAM-tak/BlenderGameRig/releases/tag/v1.4.1
