### ISSUE TITLE
Module not found after install

### ISSUE THREAD

**Issue by Neophos** [SAM-tak/BlenderGameRig#3]
Operating system: Ubuntu Unity 20.04
Blender version: 2.91

When downloading and installing, I get the error message "ModuleNotFoundError: No Module named "BlenderGameRig1"". I figured this was some bug with the naming convention, so I renamed both the zip and the folder inside to only BlenderGameRig, no numbers. Now instead I get a longer traceback:

`Traceback (most recent call last):
  File "/snap/blender/51/2.91/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/neophos/.config/blender/2.91/scripts/addons/BlenderGameRig/__init__.py", line 43, in <module>
    from . import utils, rig_lists, generate, ui, metarig_menu
  File "/home/neophos/.config/blender/2.91/scripts/addons/BlenderGameRig/rig_lists.py", line 96, in <module>
    rigs_dict = get_rig_list("")
  File "/home/neophos/.config/blender/2.91/scripts/addons/BlenderGameRig/rig_lists.py", line 64, in get_rig_list
    rig = utils.get_rig_type(module_name)
  File "/home/neophos/.config/blender/2.91/scripts/addons/BlenderGameRig/utils.py", line 406, in get_rig_type
    submod = importlib.import_module(rig_module_name(rig_type), package=MODULE_NAME)
  File "/snap/blender/51/2.91/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'gamerig'`

It doesn't seem to span from the MODULE_NAME-constant, as changing that does not change the error.

**Comment by SAM-tak** [comment]
Thanks for your feed back.
I made a mistake when make a zip archive...
